//RC4 https://obfuscator.io/

var arrLSN = [
  'localhost',
  'id.toko-wa.com',
  'www.bantuban.com',
  'bantuban.com',
  'bridaloka.com',
  'www.bridaloka.com',
  'mediaalfaruq.com',
  'www.mediaalfaruq.com',
  'griyamuslim.web.id',
  'www.griyamuslim.web.id',
  'giantindonesia.com',
  'www.giantindonesia.com',
  'kolamterpal.net',
  'www.kolamterpal.net',
  'duniabaju.com',
  'www.duniabaju.com',
  'varashoilnusantara.com',
  'www.varashoilnusantara.com',
  'pekenonline.com',
  'www.pekenonline.com',
  'luonggia.store',
  'www.luonggia.store',
  'noithat.store',
  'www.noithat.store',
  'tokooey.com',
  'www.tokooey.com',
];
